//NESTED TRY CATCH BLOCK

class DemoExce3 {
	public static void main(String[] args) {
		try
		{
			int x = 10/0;
			System.out.println(x);
		}
		catch(ArithmeticException ae) {
			System.out.println("zero allowed nahii hai");
		}
		try {
			int y[] = {10,20};
			y[4] = 9;
			System.out.println(y);
		}
		catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("Aukat se bhar ja rahe ho");
		}
	}

catch(Exception ae) {
	System.out.println(ae);
}
}

